trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "K8S Terraform Azure!"
  displayName: 'Run a one-line script'

- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa.pub'

# 🧩 Install Terraform (Fully Qualified Task)
- task: JasonBJohnson.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@1
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: '1.6.6'

# 🧩 Azure CLI login
- task: AzureCLI@2
  displayName: 'Azure CLI: login with service connection'
  inputs:
    azureSubscription: 'azure-resource-service-manager'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      bash "$(System.DefaultWorkingDirectory)/scripts/ensure-backend-and-run-terraform.sh" "$(storageAccountName)" "$(client_id)" "$(client_secret)" "$(publickey.secureFilePath)" "$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes"

# 🧩 Run Terraform init

# Terraform commands are executed in the AzureCLI task above so az login is available









