trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "K8S Terraform Azure!"
  displayName: 'Run a one-line script'

- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa.pub'

# 🧩 Install Terraform (Fully Qualified Task)
- task: JasonBJohnson.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@1
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: '1.6.6'

# 🧩 Azure CLI login
- task: AzureCLI@2
  displayName: 'Azure CLI: login with service connection'
  inputs:
    azureSubscription: 'azure-resource-service-manager'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      set -euo pipefail
      echo 'Azure login info:'
      az account show

      echo 'Defensive checks before running terraform'
      # Configure Terraform to use Service Principal auth via environment variables
      export ARM_CLIENT_ID="$(client_id)"
      export ARM_CLIENT_SECRET="$(client_secret)"
      export ARM_SUBSCRIPTION_ID="$(az account show --query id -o tsv)"
      export ARM_TENANT_ID="$(az account show --query tenantId -o tsv)"

      if ! command -v terraform >/dev/null 2>&1; then
        echo "ERROR: terraform is not installed or not on PATH. Ensure the Terraform installer task ran earlier and added terraform to PATH."
        exit 1
      fi
      terraform --version

      WORKDIR="$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes"
      if [ ! -d "$WORKDIR" ]; then
        echo "ERROR: working directory does not exist: $WORKDIR"
        exit 1
      fi
      # Ensure backend storage account and container exist (create if missing)
      SA_NAME="storageacctmanju17099"
      SA_RG="terraform-backend-rg"
      SA_LOCATION="westeurope"

      echo "Checking storage account $SA_NAME in resource group $SA_RG"
      SA_ID=$(az storage account show --name "$SA_NAME" --resource-group "$SA_RG" --query id -o tsv 2>/dev/null || true)
      if [ -z "$SA_ID" ]; then
        echo "Storage account $SA_NAME not found in resource group $SA_RG. Attempting to create it..."
        if [ "$(az group exists -n $SA_RG)" != "true" ]; then
          echo "Resource group $SA_RG not found. Creating resource group $SA_RG in $SA_LOCATION"
          az group create --name "$SA_RG" --location "$SA_LOCATION" || { echo "Failed to create resource group $SA_RG"; exit 1; }
        fi
        az storage account create --name "$SA_NAME" --resource-group "$SA_RG" --location "$SA_LOCATION" --sku Standard_LRS --kind StorageV2 || { echo "Failed to create storage account $SA_NAME"; exit 1; }
        SA_ID=$(az storage account show --name "$SA_NAME" --resource-group "$SA_RG" --query id -o tsv)
        echo "Created storage account: $SA_ID"
        echo "Creating blob container 'terraform-state' using AD auth (may require role assignment)"
        az storage container create --account-name "$SA_NAME" --name terraform-state --auth-mode login || echo "Warning: failed to create container with AD auth. It may already exist or role assignment is required."
      else
        echo "Found storage account: $SA_ID"
      fi

      if [ -n "$SA_ID" ]; then
        echo "Ensuring service principal $ARM_CLIENT_ID has 'Storage Blob Data Contributor' on $SA_ID"
        az role assignment create --assignee "$ARM_CLIENT_ID" --role "Storage Blob Data Contributor" --scope "$SA_ID" 2>/dev/null || echo "Warning: role assignment may have failed or already exists. Ensure the caller has permission to assign roles."
      fi

      echo 'Running terraform init'
      cd "$WORKDIR"
      terraform init -backend-config="resource_group_name=terraform-backend-rg" -backend-config="storage_account_name=storageacctmanju17099" -backend-config="container_name=terraform-state" -backend-config="key=kubernetes-dev.tfstate"

      echo 'Running terraform apply'
      terraform apply -auto-approve -var "client_id=$(client_id)" -var "client_secret=$(client_secret)" -var "ssh_public_key=$(publickey.secureFilePath)"

# 🧩 Run Terraform init

# Terraform commands are executed in the AzureCLI task above so az login is available









