trigger:
  branches:
    include:
    - main
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: CmdLine@2
      displayName: 'Run a one-line script'
      inputs:
        script: echo "K8S Terraform Azure!"
    - task: DownloadSecureFile@1
      name: publickey
      inputs:
        secureFile: 'azure_rsa.pub'
    - task: JasonBJohnson.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: '1.6.6'
    - task: TerraformCLI@2
      inputs:
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
        backendType: 'azurerm'
        backendServiceArm: 'azure-resource-service-manager'
        ensureBackend: true
        backendAzureRmResourceGroupName: 'terraform-backend-rg'
        backendAzureRmResourceGroupLocation: 'westeurope'
        backendAzureRmStorageAccountName: 'storageaccthello'
        backendAzureRmContainerName: 'storageaccthellocontainer'
        backendAzureRmKey: 'kubernetes-dev.tfstate'
        allowTelemetryCollection: true
    - task: TerraformCLI@2
      inputs:
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
        environmentServiceName: 'azure-resource-service-manager'
        commandOptions: >
          -var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)


# Terraform Destroy
# - task: TerraformCLI@0
#   displayName: 'Terraform Destroy'
#   inputs:
#     command: 'destroy'
#     workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
#     environmentServiceName: 'azure-resource-service-manager'
#     commandOptions: >
#       -auto-approve
#       -var client_id=$(client_id)
#       -var client_secret=$(client_secret)
#       -var ssh_public_key=$(publickey.secureFilePath)

    